import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import Database from "better-sqlite3";
import path from "path";
import fs from "fs";
import * as schema from "./schema";
import { getDataDir, getMigrationsDir } from "@/lib/paths";

// Database file path: writable data directory (injected by the main process as APP_DATA_DIR=userData/data when packaged with Electron)
const DB_DIR = getDataDir();
const DB_PATH = path.join(DB_DIR, "sqlite.db");
// Migration files directory (generated by drizzle-kit, committed to the repo; points to resources/drizzle when packaged)
const MIGRATIONS_DIR = getMigrationsDir();

// Ensure the data directory exists
if (!fs.existsSync(DB_DIR)) {
  fs.mkdirSync(DB_DIR, { recursive: true });
}

// Create the better-sqlite3 connection instance
const sqlite = new Database(DB_PATH);

// Enable WAL mode for better concurrent read/write performance.
// Skip during the next build phase: journal_mode=WAL rewrites the DB file header and requires
// a brief exclusive lock; concurrent workers importing this module during the build race for
// that lock and trigger "database is locked".
// WAL is a persistent property of the DB file — setting it once at runtime (next start / Electron) is enough.
if (process.env.NEXT_PHASE !== "phase-production-build") {
  sqlite.pragma("journal_mode = WAL");
}
// Enable foreign-key constraints (a per-connection pragma — does not write to the DB file or contend on locks, safe during build)
sqlite.pragma("foreign_keys = ON");

// Create the Drizzle ORM instance with the schema bound for relational queries
export const db = drizzle(sqlite, { schema });

// Zero-config: apply migrations automatically on startup so a fresh clone or empty DB gets all tables created.
// (Fixes issue #2 "no such table: projects" — data/ is gitignored so a fresh checkout has no tables.)
// Skip during the next build phase: concurrent workers importing this module during the build would all
// try to migrate the same empty DB simultaneously, triggering race conditions ("duplicate column", etc.).
// Migrations only need to run once at runtime (next start / Electron).
if (process.env.NEXT_PHASE !== "phase-production-build") {
  try {
    if (fs.existsSync(MIGRATIONS_DIR)) {
      migrate(db, { migrationsFolder: MIGRATIONS_DIR });
    }
  } catch (err) {
    console.error("Database migration failed:", err);
  }
}

// Compatibility wrapper for functional-style callers
export function getDb() {
  return db;
}
